sudo: required

language: node_js
node_js:
  - '10.15.3'

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - ./node_modules

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

before_script:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run lint
  - npm run build --prod
  - docker build -t vkarpeniuk/find-and-go .
  - docker tag vkarpeniuk/find-and-go registry.heroku.com/docker-find-and-go/web

deploy:
  provider: script
  script: docker push registry.heroku.com/docker-find-and-go/web;
    heroku container:release web --app docker-find-and-go;
  on:
    branch: master
